import type { Exercise } from "../domain/models";

// Product taxonomy seed, not an approved prescription or scientific ranking.
export const catalog: Exercise[] = [
  {
    id: "chest-press",
    name: "머신 체스트 프레스",
    group: "가슴",
    equipment: "머신",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "dumbbell-bench",
    name: "덤벨 벤치 프레스",
    group: "가슴",
    equipment: "덤벨",
    loadMode: "per_hand",
    review: "catalog_draft",
  },
  {
    id: "lat-pulldown",
    name: "랫풀다운",
    group: "등",
    equipment: "케이블",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "cable-row",
    name: "케이블 로우",
    group: "등",
    equipment: "케이블",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "shoulder-press",
    name: "머신 숄더 프레스",
    group: "어깨",
    equipment: "머신",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "lateral-raise",
    name: "레터럴 레이즈",
    group: "어깨",
    equipment: "덤벨",
    loadMode: "per_hand",
    review: "catalog_draft",
  },
  {
    id: "cable-curl",
    name: "케이블 컬",
    group: "팔",
    equipment: "케이블",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "overhead-extension",
    name: "오버헤드 익스텐션",
    group: "팔",
    equipment: "케이블",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "squat",
    name: "바벨 스쿼트",
    group: "하체",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
  },
  {
    id: "leg-press",
    name: "레그 프레스",
    group: "하체",
    equipment: "머신",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "leg-curl",
    name: "레그 컬",
    group: "하체",
    equipment: "머신",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "plank",
    name: "플랭크",
    group: "코어",
    equipment: "맨몸",
    loadMode: "timed",
    review: "catalog_draft",
  },
];
