import type { Exercise } from "../domain/models";

// Product taxonomy seed, not an approved prescription or scientific ranking.
export const catalog: Exercise[] = [
  {
    id: "chest-press",
    name: "머신 체스트 프레스",
    group: "가슴",
    subgroup: "중부",
    equipment: "머신",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "dumbbell-bench",
    name: "덤벨 벤치 프레스",
    group: "가슴",
    subgroup: "중부",
    equipment: "덤벨",
    loadMode: "per_hand",
    review: "catalog_draft",
  },
  {
    id: "lat-pulldown",
    name: "랫풀다운",
    group: "등",
    subgroup: "광배",
    equipment: "케이블",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "cable-row",
    name: "케이블 로우",
    group: "등",
    subgroup: "상부 등",
    equipment: "케이블",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "shoulder-press",
    name: "머신 숄더 프레스",
    group: "어깨",
    subgroup: "전면",
    equipment: "머신",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "lateral-raise",
    name: "레터럴 레이즈",
    aliases: ["덤벨 사이드 레터럴 레이즈", "사이드 레이즈"],
    group: "어깨",
    subgroup: "측면",
    equipment: "덤벨",
    loadMode: "per_hand",
    review: "catalog_draft",
  },
  {
    id: "cable-curl",
    name: "케이블 컬",
    group: "팔",
    subgroup: "이두",
    equipment: "케이블",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "overhead-extension",
    name: "오버헤드 익스텐션",
    group: "팔",
    subgroup: "삼두",
    equipment: "케이블",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "squat",
    name: "바벨 스쿼트",
    group: "하체",
    subgroup: "허벅지 앞쪽",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
  },
  {
    id: "leg-press",
    name: "레그 프레스",
    group: "하체",
    subgroup: "허벅지 앞쪽",
    equipment: "머신",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "leg-curl",
    name: "레그 컬",
    group: "하체",
    subgroup: "허벅지 뒤쪽",
    equipment: "머신",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "plank",
    name: "플랭크",
    group: "코어",
    subgroup: "복부",
    equipment: "맨몸",
    loadMode: "timed",
    review: "catalog_draft",
  },
  {
    id: "barbell-bench",
    name: "바벨 벤치 프레스",
    group: "가슴",
    subgroup: "중부",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
    aliases: ["벤치프레스", "3대운동"],
  },
  {
    id: "barbell-incline-bench",
    name: "바벨 인클라인 벤치 프레스",
    group: "가슴",
    subgroup: "상부",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
  },
  {
    id: "barbell-decline-bench",
    name: "바벨 디클라인 벤치 프레스",
    group: "가슴",
    subgroup: "하부",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
  },
  {
    id: "barbell-floor-press",
    name: "바벨 플로어 프레스",
    group: "가슴",
    subgroup: "중부",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
  },
  {
    id: "barbell-deadlift",
    name: "바벨 데드리프트",
    group: "하체",
    subgroup: "하체 전체",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
    aliases: ["컨벤셔널 데드리프트", "3대운동"],
  },
  {
    id: "barbell-rdl",
    name: "바벨 루마니안 데드리프트",
    group: "하체",
    subgroup: "허벅지 뒤쪽",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
    aliases: ["RDL"],
  },
  {
    id: "barbell-sumo-deadlift",
    name: "바벨 스모 데드리프트",
    group: "하체",
    subgroup: "하체 전체",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
  },
  {
    id: "barbell-front-squat",
    name: "바벨 프론트 스쿼트",
    group: "하체",
    subgroup: "허벅지 앞쪽",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
  },
  {
    id: "barbell-split-squat",
    name: "바벨 스플릿 스쿼트",
    group: "하체",
    subgroup: "허벅지 앞쪽",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
  },
  {
    id: "barbell-hip-thrust",
    name: "바벨 힙 쓰러스트",
    group: "하체",
    subgroup: "둔부",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
    aliases: ["힙스러스트"],
  },
  {
    id: "barbell-calf-raise",
    name: "바벨 카프 레이즈",
    group: "하체",
    subgroup: "종아리",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
  },
  {
    id: "barbell-bent-row",
    name: "바벨 벤트오버 로우",
    group: "등",
    subgroup: "등 전체",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
    aliases: ["바벨 로우"],
  },
  {
    id: "barbell-pendlay-row",
    name: "바벨 펜들레이 로우",
    group: "등",
    subgroup: "등 전체",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
  },
  {
    id: "barbell-overhead-press",
    name: "바벨 오버헤드 프레스",
    group: "어깨",
    subgroup: "전면",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
    aliases: ["밀리터리 프레스", "OHP"],
  },
  {
    id: "barbell-curl",
    name: "바벨 컬",
    group: "팔",
    subgroup: "이두",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
  },
  {
    id: "barbell-close-grip-bench",
    name: "바벨 클로즈그립 벤치 프레스",
    group: "팔",
    subgroup: "삼두",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
  },
  {
    id: "barbell-skull-crusher",
    name: "바벨 라잉 트라이셉스 익스텐션",
    group: "팔",
    subgroup: "삼두",
    equipment: "바벨",
    loadMode: "total",
    review: "catalog_draft",
    aliases: ["스컬 크러셔"],
  },
  {
    id: "dumbbell-front-raise",
    name: "덤벨 프론트 레이즈",
    group: "어깨",
    subgroup: "전면",
    equipment: "덤벨",
    loadMode: "per_hand",
    review: "catalog_draft",
  },
  {
    id: "dumbbell-rear-raise",
    name: "덤벨 벤트오버 레터럴 레이즈",
    group: "어깨",
    subgroup: "후면",
    equipment: "덤벨",
    loadMode: "per_hand",
    review: "catalog_draft",
    aliases: ["리어 델트 레이즈", "후면 레이즈"],
  },
  {
    id: "cable-behind-raise",
    name: "케이블 비하인드백 레터럴 레이즈",
    group: "어깨",
    subgroup: "측면",
    equipment: "케이블",
    loadMode: "machine",
    review: "catalog_draft",
    aliases: ["비하인드 레이즈"],
  },
  {
    id: "cable-lateral-raise",
    name: "케이블 사이드 레터럴 레이즈",
    group: "어깨",
    subgroup: "측면",
    equipment: "케이블",
    loadMode: "machine",
    review: "catalog_draft",
  },
  {
    id: "reverse-pec-deck",
    name: "리버스 펙덱",
    group: "어깨",
    subgroup: "후면",
    equipment: "머신",
    loadMode: "machine",
    review: "catalog_draft",
    aliases: ["리어 델트 플라이"],
  },
];
